version: '3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/home/node/app
    tty: true
    ports:
      - '3001:3001'
    environment:
      DATABASE_DB: test-agro
      DATABASE_USER: brgarcias
      DATABASE_PASSWORD: 12345
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test-agro
      POSTGRES_USER: brgarcias
      POSTGRES_PASSWORD: 12345
    networks:
      - app-network

  test:
    image: node:19-alpine
    container_name: test
    working_dir: /home/node/app
    command: sh -c "npm test && npm run test:e2e"
    volumes:
      - .:/home/node/app
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
